//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autumn.File.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autumn.File.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter [{0}] was passed as an empty element which is not permitted in this context..
        /// </summary>
        internal static string ExceptionArgumentEmpty {
            get {
                return ResourceManager.GetString("ExceptionArgumentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbstractDictionary&lt;TKey, TValue&gt;[int] access violation: when IsIndexed is false, you may not access items by numeric index..
        /// </summary>
        internal static string ExceptionDictionaryBaseIndex {
            get {
                return ResourceManager.GetString("ExceptionDictionaryBaseIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EXIF tag contains a DateTime that was not understood: [{0}].
        /// </summary>
        internal static string ExceptionExifDateParseFail {
            get {
                return ResourceManager.GetString("ExceptionExifDateParseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EXIF tag for DateTime Taken, DateTime Modified or DateTime Digitized was not found.
        /// </summary>
        internal static string ExceptionExifDateTagNotFound {
            get {
                return ResourceManager.GetString("ExceptionExifDateTagNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move file to be deleted ([{0}] -&gt; [{1}]) due to (see inner exception): {2}.
        /// </summary>
        internal static string ExceptionFileMoveThenDelete {
            get {
                return ResourceManager.GetString("ExceptionFileMoveThenDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source System.IO.FileInfo was null which is not permitted when calling instance properties..
        /// </summary>
        internal static string ExceptionFileSystemFileInfoNull {
            get {
                return ResourceManager.GetString("ExceptionFileSystemFileInfoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstOrDefault extension cannot accept null for the [{0}] parameter..
        /// </summary>
        internal static string ExceptionFirstOrDefaultNullParam {
            get {
                return ResourceManager.GetString("ExceptionFirstOrDefaultNullParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FirstWhereOrDefault extension cannot accept null for the [{0}] parameter..
        /// </summary>
        internal static string ExceptionFirstWhereOrDefault {
            get {
                return ResourceManager.GetString("ExceptionFirstWhereOrDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path and file [{0}] does not represent an existing file..
        /// </summary>
        internal static string ExceptionFullPathNotValid {
            get {
                return ResourceManager.GetString("ExceptionFullPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image file [{0}] threw an error: [{1}].
        /// </summary>
        internal static string ExceptionImageFormat {
            get {
                return ResourceManager.GetString("ExceptionImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index [{0}] was out of range. The index must be non-negative and less than the size of the collection [{1}]..
        /// </summary>
        internal static string ExceptionIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.TryEnter: The lock could not be attained after {0} milliseconds.
        /// </summary>
        internal static string ExceptionLockTimeout {
            get {
                return ResourceManager.GetString("ExceptionLockTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.TryEnter: The lock could not be attained after {0} milliseconds.
        /// </summary>
        internal static string ExceptionLockTimeout1 {
            get {
                return ResourceManager.GetString("ExceptionLockTimeout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The array passed to this method is null which is not permitted; please pass an initialized array..
        /// </summary>
        internal static string ExceptionParamArrayNull {
            get {
                return ResourceManager.GetString("ExceptionParamArrayNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse value [{0}] when parameter oncomplete is null since there would be no way to return the result..
        /// </summary>
        internal static string ExceptionParserOnCompleteNull {
            get {
                return ResourceManager.GetString("ExceptionParserOnCompleteNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file, [{0}], could not be found; please ensure this file is in the same directory as the application itself..
        /// </summary>
        internal static string ExceptionProcessConfigNotFound {
            get {
                return ResourceManager.GetString("ExceptionProcessConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration for this application was not found. The cause could be malformed XML, an empty configuration file or the configuration file, [{0}], has been moved..
        /// </summary>
        internal static string ExceptionProcessConfigSettingsNotFound {
            get {
                return ResourceManager.GetString("ExceptionProcessConfigSettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the property or field you attempted to access, [{1}], could not be found in type [{2}]..
        /// </summary>
        internal static string ExceptionPropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadFileAction: the file path was null or empty.
        /// </summary>
        internal static string ExceptionReadFileActionPathNull {
            get {
                return ResourceManager.GetString("ExceptionReadFileActionPathNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadLock: could not establish exclusive read lock access for more than {0} milliseconds.
        /// </summary>
        internal static string ExceptionReadLockDenied {
            get {
                return ResourceManager.GetString("ExceptionReadLockDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object is read-only and may not be modified.
        /// </summary>
        internal static string ExceptionReadOnlyObject {
            get {
                return ResourceManager.GetString("ExceptionReadOnlyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This property is read-only and may not be modified.
        /// </summary>
        internal static string ExceptionReadOnlyProperty {
            get {
                return ResourceManager.GetString("ExceptionReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement failed: the provided argument [{0}] was null which is not permitted.
        /// </summary>
        internal static string ExceptionRequireArgumentIsNotNull {
            get {
                return ResourceManager.GetString("ExceptionRequireArgumentIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement failed: the provided argument [{0}] was null or empty which is not permitted.
        /// </summary>
        internal static string ExceptionRequireArgumentIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionRequireArgumentIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement failed: [the provided value was null which is not permitted] {0}.
        /// </summary>
        internal static string ExceptionRequireIsNotNull {
            get {
                return ResourceManager.GetString("ExceptionRequireIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement failed: [the provided value was null or empty which is not permitted] {0}.
        /// </summary>
        internal static string ExceptionRequireIsNotNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionRequireIsNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller cannot continue the process since it cannot determine whether the source path search is recursive or not; the required key [{0}] or its value was not provided..
        /// </summary>
        internal static string ExceptionSearchIsRecursiveNotFound {
            get {
                return ResourceManager.GetString("ExceptionSearchIsRecursiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller cannot continue the process due to missing data and/or key: [{0}]. A valid source directory must be provided..
        /// </summary>
        internal static string ExceptionSettingSourceKeyNotFound {
            get {
                return ResourceManager.GetString("ExceptionSettingSourceKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the provided source cannot be null or empty.
        /// </summary>
        internal static string ExceptionSourceNullEmpty {
            get {
                return ResourceManager.GetString("ExceptionSourceNullEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller cannot continue the process because the source path provided was not found (invalid): [{0}]. A valid source directory must be provided..
        /// </summary>
        internal static string ExceptionSourcePathNotFound {
            get {
                return ResourceManager.GetString("ExceptionSourcePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WriteLock: could not establish exclusive write lock access for more than {0} milliseconds.
        /// </summary>
        internal static string ExceptionWriteLockDenied {
            get {
                return ResourceManager.GetString("ExceptionWriteLockDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}.
        /// </summary>
        internal static string FormatCommaSepPair {
            get {
                return ResourceManager.GetString("FormatCommaSepPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string FormatDelimitedDefault {
            get {
                return ResourceManager.GetString("FormatDelimitedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-duplicate-{1}.{2}.
        /// </summary>
        internal static string FormatDuplicateSuffix {
            get {
                return ResourceManager.GetString("FormatDuplicateSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception [{0}] Message [{1}]\r\n Stack [{2}].
        /// </summary>
        internal static string FormatExceptionMessage {
            get {
                return ResourceManager.GetString("FormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy:MM:d H:m:s.
        /// </summary>
        internal static string FormatExifDateTime {
            get {
                return ResourceManager.GetString("FormatExifDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .{0}.
        /// </summary>
        internal static string FormatFileExtension {
            get {
                return ResourceManager.GetString("FormatFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Index [{0}] of Total [{1}]: processing complete for file [{2}] original name [{3}].
        /// </summary>
        internal static string FormatFileProcessComplete {
            get {
                return ResourceManager.GetString("FormatFileProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.xml.
        /// </summary>
        internal static string FormatFileXml {
            get {
                return ResourceManager.GetString("FormatFileXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} = {1}.
        /// </summary>
        internal static string FormatKeyValueDefault {
            get {
                return ResourceManager.GetString("FormatKeyValueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1}].
        /// </summary>
        internal static string FormatKeyValueSet {
            get {
                return ResourceManager.GetString("FormatKeyValueSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string FormatPair {
            get {
                return ResourceManager.GetString("FormatPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _yyyyMMdd_hhmmssff.
        /// </summary>
        internal static string FormatRejectedDateTime {
            get {
                return ResourceManager.GetString("FormatRejectedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}{2}.
        /// </summary>
        internal static string FormatTriple {
            get {
                return ResourceManager.GetString("FormatTriple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string KeyWildcardAllFiles {
            get {
                return ResourceManager.GetString("KeyWildcardAllFiles", resourceCulture);
            }
        }
    }
}
